#(BOARD)

all:
	echo try: 'make clean', or 'make update'

clean:
	find . -name '*~' -delete
	find . -name '*#' -delete
	find . -name '*.s#[0-9]' -delete
	rm -f *.s#[0-9]
	rm -f *.b#[0-9]
	rm -f *.l#[0-9]
	rm -f *.job
	rm -f *.log
	rm -f *.scr
	rm -f *.pro
update:
	# git add .
	# git commit -am "update"
	# git push origin master
